-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 15:19:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Videoclub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Videoclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Videoclub` DEFAULT CHARACTER SET utf8 ;
USE `Videoclub` ;

-- -----------------------------------------------------
-- Table `Videoclub`.`Peliculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Videoclub`.`Peliculas` (
  `codigo_pelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `año` INT NOT NULL,
  `duracion` DOUBLE NULL,
  PRIMARY KEY (`codigo_pelicula`));


-- -----------------------------------------------------
-- Table `Videoclub`.`Amigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Videoclub`.`Amigos` (
  `codigo_amigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `direccion` INT NOT NULL,
  PRIMARY KEY (`codigo_amigo`));


-- -----------------------------------------------------
-- Table `Videoclub`.`Prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Videoclub`.`Prestamos` (
  `numero_alquiler` INT NOT NULL AUTO_INCREMENT,
  `fecha_fin` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `codigo_pelicula` INT NOT NULL,
  `codigo_amigo` INT NOT NULL,
  PRIMARY KEY (`numero_alquiler`, `codigo_pelicula`, `codigo_amigo`),
  INDEX `CodAmigo_idx` (`codigo_amigo` ASC) VISIBLE,
  INDEX `CodPelicula_idx` (`codigo_pelicula` ASC) VISIBLE,
  CONSTRAINT `CodAmigo`
    FOREIGN KEY (`codigo_amigo`)
    REFERENCES `Videoclub`.`Amigos` (`codigo_amigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodPelicula`
    FOREIGN KEY (`codigo_pelicula`)
    REFERENCES `Videoclub`.`Peliculas` (`codigo_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
